### ISSUE TITLE
Inject components into translations

### ISSUE THREAD

**Issue by pgom** [JSxMachina/react-i18nify#20]
I'm wondering if I'm are the only one with this kind of needs. 
On the current application I'm working on, it might be useful if we could use a component as value. For example:

```
render() {
 return I18n.t('key', { value: <Link onclick={() => } />}
}
```

In this example, `Link` returns a link with predefined set of props that we use everywhere.
@zoover, does something like this makes sense to add? If so, how would you suggest to do it?

**Comment by juampick** [comment]
Needing the same around here. Did you reach to a solution @pgom ?

**Comment by gerbenmeyer** [comment]
Still not sure whether this makes sense to add, but if anyone has a nice solution for this, feel free to make a pull request :smile:
