### ISSUE TITLE
Does this have nested values? 

### ISSUE THREAD

**Issue by michaeljota** [JSxMachina/react-i18nify#32]
Hi! I'm using this in a project, and I'm wondering if this have nested values, if so, how can you set nested strings? 

ref: http://i18next.com/translate/nesting/

**Comment by gerbenmeyer** [comment]
You mean something like this:
```
I18n.t('application', {name: 'Aad'}); // => returns {hello: "Hallo, Aad!", title: "Toffe app met i18n!"} for locale 'nl'
```
In that case, yes! :smile:

**Comment by michaeljota** [comment]
Thanks for the response. I can't tell why was that question anymore. :sweat_smile: Thanks anyway.
