### ISSUE TITLE
Uncaught TypeError: Cannot read property 'options' of undefined     at new Translate (translate.js:63)

### ISSUE THREAD

**Issue by tabletfrontend** [JSxMachina/react-i18nify#34]
I am not sure why this error is happening. Looks like something to do with the configuration of i18n.

The line at translate.js:63 is:

namespaces = namespaces || _this.i18n.options.defaultNS;

Not exactly sure where the i18n options get configured? Any ideas for this error / why i18n would be undefined?

**Comment by gerbenmeyer** [comment]
Are you sure this is an issue with react-i18nify? We don't do anything with namespaces as far as I recall.
