### ISSUE TITLE
Warning: forceUpdate(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

### ISSUE THREAD

**Issue by nuttikung** [JSxMachina/react-i18nify#36]
I get this error from console by changed locale language after using I18n.setLocale(xx) but my website is translate correctly.

For more information I use it with nextjs.

Browser : Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
OS : OSX 10.12.6 (16G29)
react-i18nify : Version 1.8.7
next :  Version latest 

<img width="1280" alt="screen shot 2017-09-25 at 11 58 54 pm" src="https://user-images.githubusercontent.com/8456620/30820966-cc1de02a-a24d-11e7-92e5-a0365a80cfa9.png">

**Comment by gerbenmeyer** [comment]
Is this issue still happening? Also, could this be because of using nextjs? Never used that myself.
