### ISSUE TITLE
React16 update

### ISSUE THREAD

**Issue by juampick** [JSxMachina/react-i18nify#37]
Hi all! 

Can we update the dependency from 15.6.2 to 16 version? What do you think? I'm having some issue in a big project with some libraries, and not sure but this is one of our dependencies, that are requiring react@15.6.2

Can anyone help? Thanks

**Comment by AlexMarvelo** [comment]
+1
In my project react-i18nify is the only lib that still requires react@15.6.2

**Comment by gerbenmeyer** [comment]
Just upgraded to react 16, and it's also a peer dependency now!
