### ISSUE TITLE
Strings are overwritten after first replacement

### ISSUE THREAD

**Issue by shanimal** [JSxMachina/react-i18nify#38]
It looks like replace is done to the original strings object (instead of a clone) So `_replace` destroys `%{age}` on the first-run, and the strings are permanently encoded with the first-run `replacements` value.

```
en : {
  really: {
    deeply: {
      nested: {
        name1: 'You are %{age} years old',
      },
    }
  }
}

t('really.deeply.nested', { age: 30 }).name1 // You are 30 years old
t('really.deeply.nested', { age: 20 }).name1 // You are 30 years old
```

expected : `// You are 20 years old`

**Comment by shanimal** [comment]
I'm guessing something like this would fix it...
```
  _replace(translation, replacements) {
    let replaced = {};
    if (typeof translation === 'string') {
      Object.keys(replacements).forEach((replacement) => {
        replaced = translation.split(`%{${replacement}}`).join(replacements[replacement]);
      });
      return replaced;
    }
    Object.keys(replaced).forEach((translationKey) => {
      replaced[translationKey] = this._replace(translation[translationKey], replacements);
    });
    return replaced;
  },
```

**Comment by shanimal** [comment]
https://github.com/JSxMachina/react-i18nify/pull/39

**Comment by gerbenmeyer** [comment]
This doesn't seem to be an issue with `_replace`, because that's using `String.replace`, which doesn't change the original string.

Also, if I change your example to the following, it's working properly.
```
t('really.deeply.nested.name1', { age: 30 }) // You are 30 years old
t('really.deeply.nested.name1', { age: 20 }) // You are 20 years old
```

**Comment by shanimal** [comment]
The part that gets overwritten is in the recursion.

`replaced[translationKey] = this._replace...`

Maybe it wasn't your intention to allow localizing and returning an entire object? I found it sueful so I thought I would create a PR.

**Comment by gerbenmeyer** [comment]
Agreed, that can be useful, so I'm happy with merging your changes to `I18n.js`. But do we really need the new React component for this?

**Comment by gerbenmeyer** [comment]
It's fixed now in the latest version, by using parts of your PR. Thanks for the catch!

**Comment by shanimal** [comment]
No we didn't need a new react component, thanks for [fixing the issue](https://github.com/JSxMachina/react-i18nify/commit/dc16ab93d17f7d64186d678bb49a1224e17190e0)
