### ISSUE TITLE
change

### ISSUE THREAD

**Issue by Butonix** [JSxMachina/react-i18nify#41]
Hi
how to switch between languages?

example ?chang=nl

**Comment by gerbenmeyer** [comment]
Just use `I18n.setLocale('nl');`

**Comment by Butonix** [comment]
I wonder how to do this user?
how can the user switch the language?

**Comment by gerbenmeyer** [comment]
You can for example have a React component with a button with an onClick handler which calls `I18n.setLocale('nl');`.

**Comment by Butonix** [comment]
nonsense, this with cookies will be a problem

**Comment by gerbenmeyer** [comment]
`react-i18nify` doesn't use cookies at all :confused:
