### ISSUE TITLE
LTS key for localization does not work as expected

### ISSUE THREAD

**Issue by eakarpov** [JSxMachina/react-i18nify#43]
Using ```<Localize value={value} dateFormat="LTS" />``` does not return 01.01.2018 12:16:20 PM as expected from moment.js documentation.
It returns 01.01.2018t20 (as using L and S key separately with t as string constant).

**Comment by gerbenmeyer** [comment]
For `dateFormat`, a key from the translations is expected. So for example, this will work:
`
I18n.setTranslations({
  en: {
    date: {
      long: 'LTS'
    }
  }
});
I18n.setLocale('en');

<Localize value={value} dateFormat="date.long" />
`

**Comment by gerbenmeyer** [comment]
Maybe I can make this easier though by just using `LTS` for `moment` when it cannot find this as a key in the translations...

**Comment by gerbenmeyer** [comment]
ok, simplified this in the latest version, `<Localize value={value} dateFormat="LTS" />` should now also work.

**Comment by eakarpov** [comment]
@gerbenmeyer thanks!
