### ISSUE TITLE
Suggestion of adding locale parameter to i18n.t

### ISSUE THREAD

**Issue by shouulysses** [JSxMachina/react-i18nify#44]
Just wanna ask if you would like to consider adding a new parameter locale to i18n.t, something like
```
t(key, replacements = {}, locale = null) {
    return this._translate(key, replacements, locale);
}

_translate(key, replacements = {}, locale = null) {
  let translation = '';
  try {
    const translationLocale = locale || this._translations[this._locale] ?
      this._locale :
      this._locale.split('-')[0];
    translation = this._fetchTranslation(
      this._translations,
      `${translationLocale}.${key}`,
      replacements.count,
    );
  } catch (err) {
    return this._handleMissingTranslation(key, replacements);
  }
  return this._replace(translation, replacements);
}
```

So that I can control the translation using state in a easier way

I know that most of the problems should have been solved by using Tag in Translate, but I received a project that is using i18n.t everywhere and I think it would be nice if I can have a easier fix for it. Thanks.

**Comment by gerbenmeyer** [comment]
For using state to manage the locale, we have the `setLocaleGetter` function available. Wouldn't that suffice in your case? You can provide a function as an argument which can get the locale from the state.

See also: https://github.com/JSxMachina/react-i18nify#setlocalegetterfn

**Comment by shouulysses** [comment]
Thanks, I will check it out.

In my case, the application is actually using react-redux-i18n, based on your react-i18nify, I have received hundreds of files using i18n.t to get its locale, and it is using window.reload() to refresh the whole app for the new locale, which makes no sense to me.

Therefore, I am looking for a easiest solution to fix this with find and replace and not getting into every files ...

**Comment by flo-sch** [comment]
@shouulysses if you use `react-redux-i18n` you should use the `setLocale` action to set the locale in the global state (using `react-redux-i18n` reducer).

```
// reducer
import { createStore, combineReducers } from 'redux'
import { i18nReducer } from 'react-redux-i18n'

const store = createStore(
    combineReducers({
        // Your own reducers...
        i18n: i18nReducer,
    })
)

// Initialization of your app (usually your entry JS file)
import { loadTranslations, setLocale, syncTranslationWithStore } from 'react-redux-i18n';

const translations = {
    en: {
        title: "Hello"
    },
    fr: {
        title: "Bonjour"
    },
    de: {
        title: "Guten Tag"
    }
};

syncTranslationWithStore(store)
store.dispatch(loadTranslations(translations))
store.dispatch(setLocale('en')); // or whatever locale your application default to

// connected LocaleSelector component
import { connect } from 'react-redux';
import { setLocale } from 'react-redux-i18n';

class LocaleSelector extends React.Component {
    render() {
        const { changeLocale, locale } = this.props;

        return <button onClick={changeLocale(locale)} />
    }
}

const mapDispatchToProps = dispatch => ({
    changeLocale: (locale) => dispatch(setLocale(locale))
})

export default connect(null, mapDispatchToProps)(LocaleSelector)

// In your app
<LocaleSelector locale="en">English</LocaleSelector>
<LocaleSelector locale="fr">French</LocaleSelector>
<LocaleSelector locale="de">Deutsch</LocaleSelector>
```
