### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by Mystify** [JSxMachina/react-i18nify#45]
Updated this morning and started getting this:

WARNING in ./node_modules/react-i18nify/build/lib/I18n.js
127:8-29 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/react-i18nify/build/lib/I18n.js
 @ ./node_modules/react-i18nify/build/index.js
 @ ./node_modules/react-redux-i18n/build/index.js

Don't really have any more information, but I can provide more if you need it. Just let me know what you need to know.

**Comment by gerbenmeyer** [comment]
That's probably related to how `moment.js` is included, we're already working on a solution.

**Comment by gerbenmeyer** [comment]
See https://github.com/JSxMachina/react-i18nify/issues/42
