### ISSUE TITLE
Add JSX/React Components support in replacements

### ISSUE THREAD

**Issue by eugeneglova** [JSxMachina/react-i18nify#46]
Can you please add any support for using components in replacements?

**Problem:**

```js
const Header = ({ children }) => <h1>{children}</h1>
const result = I18n.t('some.key', {
   replacement1: <Component>text</Component>
})
console.log(result); // something like [Object]
```

**Example workaround (not fully working):**

```js
export const t = (value, replacements) => {
  const html = I18n.t(value)
  const result = Object.keys(replacements).map(key => {
    const parts = html.split(`%{${key}}`)
    return parts.reduce(
      (acc, text, index, arr) =>
        index === arr.length - 1 ? [...acc, text] : [...acc, text, replacements[key]],
      []
    )
  })
  return _.flatten(result)
}
```

**Comment by gerbenmeyer** [comment]
We do support `dangerouslySetInnerHTML`, wouldn't that suffice for you? Just curious about the use case, and whether it cannot be solved differently.

**Comment by eugeneglova** [comment]
hey @gerbenmeyer the use case is very simple, I have some translation key `my.key` with text value like this `Hello %{replacement}`. I want to replace `replacement` with link to my page using [react router dom link](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom).

So as a result I want to call
`{I18n.t('my.key', { replacement: <Link to="/some/router/page">page name</Link> })}`
and be able to click on that page. But as a result I got `Hello [Object object]`.

As a work around I use `<a href="/some/router/page">page name</a>` but when I click on link it does  full page reload and I am not happy with it.

Another workaround is use [htmr](https://github.com/pveyes/htmr) package with mapping `{ map: { 'a' : Link }}` but instead of `<a href="">` I need to use `<a to="">` to make it work.

**Comment by gerbenmeyer** [comment]
Now I get it, I'll give it a try to see if I can get it to work :)

**Comment by gerbenmeyer** [comment]
Support for this will be added in the next major release of `react-i18nify`! If you want you can try it out already by installing `react-i18nify@next`, but it's still in the prerelease phase :)

**Comment by eugeneglova** [comment]
@gerbenmeyer cool, thanks a lot!
